// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>

typedef struct {
    const char *name;
    size_t size;
    size_t alignent;
} Layout;

const Layout LAYOUTS[] = {
    { "GdkAnchorHints", sizeof(GdkAnchorHints), alignof(GdkAnchorHints) },
    { "GdkAxisFlags", sizeof(GdkAxisFlags), alignof(GdkAxisFlags) },
    { "GdkAxisUse", sizeof(GdkAxisUse), alignof(GdkAxisUse) },
    { "GdkByteOrder", sizeof(GdkByteOrder), alignof(GdkByteOrder) },
    { "GdkColor", sizeof(GdkColor), alignof(GdkColor) },
    { "GdkCrossingMode", sizeof(GdkCrossingMode), alignof(GdkCrossingMode) },
    { "GdkCursorType", sizeof(GdkCursorType), alignof(GdkCursorType) },
    { "GdkDevicePadFeature", sizeof(GdkDevicePadFeature), alignof(GdkDevicePadFeature) },
    { "GdkDeviceToolType", sizeof(GdkDeviceToolType), alignof(GdkDeviceToolType) },
    { "GdkDeviceType", sizeof(GdkDeviceType), alignof(GdkDeviceType) },
    { "GdkDragAction", sizeof(GdkDragAction), alignof(GdkDragAction) },
    { "GdkDragCancelReason", sizeof(GdkDragCancelReason), alignof(GdkDragCancelReason) },
    { "GdkDragProtocol", sizeof(GdkDragProtocol), alignof(GdkDragProtocol) },
    { "GdkEvent", sizeof(GdkEvent), alignof(GdkEvent) },
    { "GdkEventAny", sizeof(GdkEventAny), alignof(GdkEventAny) },
    { "GdkEventButton", sizeof(GdkEventButton), alignof(GdkEventButton) },
    { "GdkEventConfigure", sizeof(GdkEventConfigure), alignof(GdkEventConfigure) },
    { "GdkEventCrossing", sizeof(GdkEventCrossing), alignof(GdkEventCrossing) },
    { "GdkEventDND", sizeof(GdkEventDND), alignof(GdkEventDND) },
    { "GdkEventExpose", sizeof(GdkEventExpose), alignof(GdkEventExpose) },
    { "GdkEventFocus", sizeof(GdkEventFocus), alignof(GdkEventFocus) },
    { "GdkEventGrabBroken", sizeof(GdkEventGrabBroken), alignof(GdkEventGrabBroken) },
    { "GdkEventKey", sizeof(GdkEventKey), alignof(GdkEventKey) },
    { "GdkEventMask", sizeof(GdkEventMask), alignof(GdkEventMask) },
    { "GdkEventMotion", sizeof(GdkEventMotion), alignof(GdkEventMotion) },
    { "GdkEventOwnerChange", sizeof(GdkEventOwnerChange), alignof(GdkEventOwnerChange) },
    { "GdkEventPadAxis", sizeof(GdkEventPadAxis), alignof(GdkEventPadAxis) },
    { "GdkEventPadButton", sizeof(GdkEventPadButton), alignof(GdkEventPadButton) },
    { "GdkEventPadGroupMode", sizeof(GdkEventPadGroupMode), alignof(GdkEventPadGroupMode) },
    { "GdkEventProperty", sizeof(GdkEventProperty), alignof(GdkEventProperty) },
    { "GdkEventProximity", sizeof(GdkEventProximity), alignof(GdkEventProximity) },
    { "GdkEventScroll", sizeof(GdkEventScroll), alignof(GdkEventScroll) },
    { "GdkEventSelection", sizeof(GdkEventSelection), alignof(GdkEventSelection) },
    { "GdkEventSetting", sizeof(GdkEventSetting), alignof(GdkEventSetting) },
    { "GdkEventTouch", sizeof(GdkEventTouch), alignof(GdkEventTouch) },
    { "GdkEventTouchpadPinch", sizeof(GdkEventTouchpadPinch), alignof(GdkEventTouchpadPinch) },
    { "GdkEventTouchpadSwipe", sizeof(GdkEventTouchpadSwipe), alignof(GdkEventTouchpadSwipe) },
    { "GdkEventType", sizeof(GdkEventType), alignof(GdkEventType) },
    { "GdkEventVisibility", sizeof(GdkEventVisibility), alignof(GdkEventVisibility) },
    { "GdkEventWindowState", sizeof(GdkEventWindowState), alignof(GdkEventWindowState) },
    { "GdkFilterReturn", sizeof(GdkFilterReturn), alignof(GdkFilterReturn) },
    { "GdkFrameClockPhase", sizeof(GdkFrameClockPhase), alignof(GdkFrameClockPhase) },
    { "GdkFullscreenMode", sizeof(GdkFullscreenMode), alignof(GdkFullscreenMode) },
    { "GdkGLError", sizeof(GdkGLError), alignof(GdkGLError) },
    { "GdkGeometry", sizeof(GdkGeometry), alignof(GdkGeometry) },
    { "GdkGrabOwnership", sizeof(GdkGrabOwnership), alignof(GdkGrabOwnership) },
    { "GdkGrabStatus", sizeof(GdkGrabStatus), alignof(GdkGrabStatus) },
    { "GdkGravity", sizeof(GdkGravity), alignof(GdkGravity) },
    { "GdkInputMode", sizeof(GdkInputMode), alignof(GdkInputMode) },
    { "GdkInputSource", sizeof(GdkInputSource), alignof(GdkInputSource) },
    { "GdkKeymapKey", sizeof(GdkKeymapKey), alignof(GdkKeymapKey) },
    { "GdkModifierIntent", sizeof(GdkModifierIntent), alignof(GdkModifierIntent) },
    { "GdkModifierType", sizeof(GdkModifierType), alignof(GdkModifierType) },
    { "GdkNotifyType", sizeof(GdkNotifyType), alignof(GdkNotifyType) },
    { "GdkOwnerChange", sizeof(GdkOwnerChange), alignof(GdkOwnerChange) },
    { "GdkPoint", sizeof(GdkPoint), alignof(GdkPoint) },
    { "GdkPropMode", sizeof(GdkPropMode), alignof(GdkPropMode) },
    { "GdkPropertyState", sizeof(GdkPropertyState), alignof(GdkPropertyState) },
    { "GdkRGBA", sizeof(GdkRGBA), alignof(GdkRGBA) },
    { "GdkRectangle", sizeof(GdkRectangle), alignof(GdkRectangle) },
    { "GdkScrollDirection", sizeof(GdkScrollDirection), alignof(GdkScrollDirection) },
    { "GdkSeat", sizeof(GdkSeat), alignof(GdkSeat) },
    { "GdkSeatCapabilities", sizeof(GdkSeatCapabilities), alignof(GdkSeatCapabilities) },
    { "GdkSettingAction", sizeof(GdkSettingAction), alignof(GdkSettingAction) },
    { "GdkStatus", sizeof(GdkStatus), alignof(GdkStatus) },
    { "GdkSubpixelLayout", sizeof(GdkSubpixelLayout), alignof(GdkSubpixelLayout) },
    { "GdkTimeCoord", sizeof(GdkTimeCoord), alignof(GdkTimeCoord) },
    { "GdkTouchpadGesturePhase", sizeof(GdkTouchpadGesturePhase), alignof(GdkTouchpadGesturePhase) },
    { "GdkVisibilityState", sizeof(GdkVisibilityState), alignof(GdkVisibilityState) },
    { "GdkVisualType", sizeof(GdkVisualType), alignof(GdkVisualType) },
    { "GdkWMDecoration", sizeof(GdkWMDecoration), alignof(GdkWMDecoration) },
    { "GdkWMFunction", sizeof(GdkWMFunction), alignof(GdkWMFunction) },
    { "GdkWindowAttr", sizeof(GdkWindowAttr), alignof(GdkWindowAttr) },
    { "GdkWindowAttributesType", sizeof(GdkWindowAttributesType), alignof(GdkWindowAttributesType) },
    { "GdkWindowClass", sizeof(GdkWindowClass), alignof(GdkWindowClass) },
    { "GdkWindowEdge", sizeof(GdkWindowEdge), alignof(GdkWindowEdge) },
    { "GdkWindowHints", sizeof(GdkWindowHints), alignof(GdkWindowHints) },
    { "GdkWindowState", sizeof(GdkWindowState), alignof(GdkWindowState) },
    { "GdkWindowType", sizeof(GdkWindowType), alignof(GdkWindowType) },
    { "GdkWindowTypeHint", sizeof(GdkWindowTypeHint), alignof(GdkWindowTypeHint) },
    { "GdkWindowWindowClass", sizeof(GdkWindowWindowClass), alignof(GdkWindowWindowClass) }
};

const Layout *c_layouts(size_t *n) {
    *n = sizeof(LAYOUTS) / sizeof(Layout);
    return LAYOUTS;
}
