// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>

typedef struct {
    const char *name;
    size_t size;
    size_t alignent;
} Layout;

const Layout LAYOUTS[] = {
    { "PangoAlignment", sizeof(PangoAlignment), alignof(PangoAlignment) },
    { "PangoAnalysis", sizeof(PangoAnalysis), alignof(PangoAnalysis) },
    { "PangoAttrClass", sizeof(PangoAttrClass), alignof(PangoAttrClass) },
    { "PangoAttrColor", sizeof(PangoAttrColor), alignof(PangoAttrColor) },
    { "PangoAttrFloat", sizeof(PangoAttrFloat), alignof(PangoAttrFloat) },
    { "PangoAttrFontDesc", sizeof(PangoAttrFontDesc), alignof(PangoAttrFontDesc) },
    { "PangoAttrFontFeatures", sizeof(PangoAttrFontFeatures), alignof(PangoAttrFontFeatures) },
    { "PangoAttrInt", sizeof(PangoAttrInt), alignof(PangoAttrInt) },
    { "PangoAttrLanguage", sizeof(PangoAttrLanguage), alignof(PangoAttrLanguage) },
    { "PangoAttrShape", sizeof(PangoAttrShape), alignof(PangoAttrShape) },
    { "PangoAttrSize", sizeof(PangoAttrSize), alignof(PangoAttrSize) },
    { "PangoAttrString", sizeof(PangoAttrString), alignof(PangoAttrString) },
    { "PangoAttrType", sizeof(PangoAttrType), alignof(PangoAttrType) },
    { "PangoAttribute", sizeof(PangoAttribute), alignof(PangoAttribute) },
    { "PangoBidiType", sizeof(PangoBidiType), alignof(PangoBidiType) },
    { "PangoColor", sizeof(PangoColor), alignof(PangoColor) },
    { "PangoCoverageLevel", sizeof(PangoCoverageLevel), alignof(PangoCoverageLevel) },
    { "PangoDirection", sizeof(PangoDirection), alignof(PangoDirection) },
    { "PangoEllipsizeMode", sizeof(PangoEllipsizeMode), alignof(PangoEllipsizeMode) },
    { "PangoEngine", sizeof(PangoEngine), alignof(PangoEngine) },
    { "PangoEngineClass", sizeof(PangoEngineClass), alignof(PangoEngineClass) },
    { "PangoEngineInfo", sizeof(PangoEngineInfo), alignof(PangoEngineInfo) },
    { "PangoEngineLang", sizeof(PangoEngineLang), alignof(PangoEngineLang) },
    { "PangoEngineLangClass", sizeof(PangoEngineLangClass), alignof(PangoEngineLangClass) },
    { "PangoEngineScriptInfo", sizeof(PangoEngineScriptInfo), alignof(PangoEngineScriptInfo) },
    { "PangoEngineShape", sizeof(PangoEngineShape), alignof(PangoEngineShape) },
    { "PangoEngineShapeClass", sizeof(PangoEngineShapeClass), alignof(PangoEngineShapeClass) },
    { "PangoFont", sizeof(PangoFont), alignof(PangoFont) },
    { "PangoFontClass", sizeof(PangoFontClass), alignof(PangoFontClass) },
    { "PangoFontFace", sizeof(PangoFontFace), alignof(PangoFontFace) },
    { "PangoFontFaceClass", sizeof(PangoFontFaceClass), alignof(PangoFontFaceClass) },
    { "PangoFontFamily", sizeof(PangoFontFamily), alignof(PangoFontFamily) },
    { "PangoFontFamilyClass", sizeof(PangoFontFamilyClass), alignof(PangoFontFamilyClass) },
    { "PangoFontMap", sizeof(PangoFontMap), alignof(PangoFontMap) },
    { "PangoFontMapClass", sizeof(PangoFontMapClass), alignof(PangoFontMapClass) },
    { "PangoFontMask", sizeof(PangoFontMask), alignof(PangoFontMask) },
    { "PangoFontMetrics", sizeof(PangoFontMetrics), alignof(PangoFontMetrics) },
    { "PangoFontset", sizeof(PangoFontset), alignof(PangoFontset) },
    { "PangoFontsetClass", sizeof(PangoFontsetClass), alignof(PangoFontsetClass) },
    { "PangoGlyph", sizeof(PangoGlyph), alignof(PangoGlyph) },
    { "PangoGlyphGeometry", sizeof(PangoGlyphGeometry), alignof(PangoGlyphGeometry) },
    { "PangoGlyphInfo", sizeof(PangoGlyphInfo), alignof(PangoGlyphInfo) },
    { "PangoGlyphItem", sizeof(PangoGlyphItem), alignof(PangoGlyphItem) },
    { "PangoGlyphItemIter", sizeof(PangoGlyphItemIter), alignof(PangoGlyphItemIter) },
    { "PangoGlyphString", sizeof(PangoGlyphString), alignof(PangoGlyphString) },
    { "PangoGlyphUnit", sizeof(PangoGlyphUnit), alignof(PangoGlyphUnit) },
    { "PangoGlyphVisAttr", sizeof(PangoGlyphVisAttr), alignof(PangoGlyphVisAttr) },
    { "PangoGravity", sizeof(PangoGravity), alignof(PangoGravity) },
    { "PangoGravityHint", sizeof(PangoGravityHint), alignof(PangoGravityHint) },
    { "PangoIncludedModule", sizeof(PangoIncludedModule), alignof(PangoIncludedModule) },
    { "PangoItem", sizeof(PangoItem), alignof(PangoItem) },
    { "PangoLayoutRun", sizeof(PangoLayoutRun), alignof(PangoLayoutRun) },
    { "PangoMatrix", sizeof(PangoMatrix), alignof(PangoMatrix) },
    { "PangoOverline", sizeof(PangoOverline), alignof(PangoOverline) },
    { "PangoRectangle", sizeof(PangoRectangle), alignof(PangoRectangle) },
    { "PangoRenderPart", sizeof(PangoRenderPart), alignof(PangoRenderPart) },
    { "PangoRenderer", sizeof(PangoRenderer), alignof(PangoRenderer) },
    { "PangoRendererClass", sizeof(PangoRendererClass), alignof(PangoRendererClass) },
    { "PangoScript", sizeof(PangoScript), alignof(PangoScript) },
    { "PangoShapeFlags", sizeof(PangoShapeFlags), alignof(PangoShapeFlags) },
    { "PangoShowFlags", sizeof(PangoShowFlags), alignof(PangoShowFlags) },
    { "PangoStretch", sizeof(PangoStretch), alignof(PangoStretch) },
    { "PangoStyle", sizeof(PangoStyle), alignof(PangoStyle) },
    { "PangoTabAlign", sizeof(PangoTabAlign), alignof(PangoTabAlign) },
    { "PangoUnderline", sizeof(PangoUnderline), alignof(PangoUnderline) },
    { "PangoVariant", sizeof(PangoVariant), alignof(PangoVariant) },
    { "PangoWeight", sizeof(PangoWeight), alignof(PangoWeight) },
    { "PangoWrapMode", sizeof(PangoWrapMode), alignof(PangoWrapMode) }
};

const Layout *c_layouts(size_t *n) {
    *n = sizeof(LAYOUTS) / sizeof(Layout);
    return LAYOUTS;
}
