// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>
int main() {
    printf("%s;%zu;%zu", "PangoAlignment", sizeof(PangoAlignment), alignof(PangoAlignment));
    printf("%s;%zu;%zu", "PangoAnalysis", sizeof(PangoAnalysis), alignof(PangoAnalysis));
    printf("%s;%zu;%zu", "PangoAttrClass", sizeof(PangoAttrClass), alignof(PangoAttrClass));
    printf("%s;%zu;%zu", "PangoAttrColor", sizeof(PangoAttrColor), alignof(PangoAttrColor));
    printf("%s;%zu;%zu", "PangoAttrFloat", sizeof(PangoAttrFloat), alignof(PangoAttrFloat));
    printf("%s;%zu;%zu", "PangoAttrFontDesc", sizeof(PangoAttrFontDesc), alignof(PangoAttrFontDesc));
    printf("%s;%zu;%zu", "PangoAttrFontFeatures", sizeof(PangoAttrFontFeatures), alignof(PangoAttrFontFeatures));
    printf("%s;%zu;%zu", "PangoAttrInt", sizeof(PangoAttrInt), alignof(PangoAttrInt));
    printf("%s;%zu;%zu", "PangoAttrLanguage", sizeof(PangoAttrLanguage), alignof(PangoAttrLanguage));
    printf("%s;%zu;%zu", "PangoAttrShape", sizeof(PangoAttrShape), alignof(PangoAttrShape));
    printf("%s;%zu;%zu", "PangoAttrSize", sizeof(PangoAttrSize), alignof(PangoAttrSize));
    printf("%s;%zu;%zu", "PangoAttrString", sizeof(PangoAttrString), alignof(PangoAttrString));
    printf("%s;%zu;%zu", "PangoAttrType", sizeof(PangoAttrType), alignof(PangoAttrType));
    printf("%s;%zu;%zu", "PangoAttribute", sizeof(PangoAttribute), alignof(PangoAttribute));
    printf("%s;%zu;%zu", "PangoBidiType", sizeof(PangoBidiType), alignof(PangoBidiType));
    printf("%s;%zu;%zu", "PangoColor", sizeof(PangoColor), alignof(PangoColor));
    printf("%s;%zu;%zu", "PangoCoverageLevel", sizeof(PangoCoverageLevel), alignof(PangoCoverageLevel));
    printf("%s;%zu;%zu", "PangoDirection", sizeof(PangoDirection), alignof(PangoDirection));
    printf("%s;%zu;%zu", "PangoEllipsizeMode", sizeof(PangoEllipsizeMode), alignof(PangoEllipsizeMode));
    printf("%s;%zu;%zu", "PangoEngine", sizeof(PangoEngine), alignof(PangoEngine));
    printf("%s;%zu;%zu", "PangoEngineClass", sizeof(PangoEngineClass), alignof(PangoEngineClass));
    printf("%s;%zu;%zu", "PangoEngineInfo", sizeof(PangoEngineInfo), alignof(PangoEngineInfo));
    printf("%s;%zu;%zu", "PangoEngineLang", sizeof(PangoEngineLang), alignof(PangoEngineLang));
    printf("%s;%zu;%zu", "PangoEngineLangClass", sizeof(PangoEngineLangClass), alignof(PangoEngineLangClass));
    printf("%s;%zu;%zu", "PangoEngineScriptInfo", sizeof(PangoEngineScriptInfo), alignof(PangoEngineScriptInfo));
    printf("%s;%zu;%zu", "PangoEngineShape", sizeof(PangoEngineShape), alignof(PangoEngineShape));
    printf("%s;%zu;%zu", "PangoEngineShapeClass", sizeof(PangoEngineShapeClass), alignof(PangoEngineShapeClass));
    printf("%s;%zu;%zu", "PangoFont", sizeof(PangoFont), alignof(PangoFont));
    printf("%s;%zu;%zu", "PangoFontClass", sizeof(PangoFontClass), alignof(PangoFontClass));
    printf("%s;%zu;%zu", "PangoFontFace", sizeof(PangoFontFace), alignof(PangoFontFace));
    printf("%s;%zu;%zu", "PangoFontFaceClass", sizeof(PangoFontFaceClass), alignof(PangoFontFaceClass));
    printf("%s;%zu;%zu", "PangoFontFamily", sizeof(PangoFontFamily), alignof(PangoFontFamily));
    printf("%s;%zu;%zu", "PangoFontFamilyClass", sizeof(PangoFontFamilyClass), alignof(PangoFontFamilyClass));
    printf("%s;%zu;%zu", "PangoFontMap", sizeof(PangoFontMap), alignof(PangoFontMap));
    printf("%s;%zu;%zu", "PangoFontMapClass", sizeof(PangoFontMapClass), alignof(PangoFontMapClass));
    printf("%s;%zu;%zu", "PangoFontMask", sizeof(PangoFontMask), alignof(PangoFontMask));
    printf("%s;%zu;%zu", "PangoFontMetrics", sizeof(PangoFontMetrics), alignof(PangoFontMetrics));
    printf("%s;%zu;%zu", "PangoFontset", sizeof(PangoFontset), alignof(PangoFontset));
    printf("%s;%zu;%zu", "PangoFontsetClass", sizeof(PangoFontsetClass), alignof(PangoFontsetClass));
    printf("%s;%zu;%zu", "PangoGlyph", sizeof(PangoGlyph), alignof(PangoGlyph));
    printf("%s;%zu;%zu", "PangoGlyphGeometry", sizeof(PangoGlyphGeometry), alignof(PangoGlyphGeometry));
    printf("%s;%zu;%zu", "PangoGlyphInfo", sizeof(PangoGlyphInfo), alignof(PangoGlyphInfo));
    printf("%s;%zu;%zu", "PangoGlyphItem", sizeof(PangoGlyphItem), alignof(PangoGlyphItem));
    printf("%s;%zu;%zu", "PangoGlyphItemIter", sizeof(PangoGlyphItemIter), alignof(PangoGlyphItemIter));
    printf("%s;%zu;%zu", "PangoGlyphString", sizeof(PangoGlyphString), alignof(PangoGlyphString));
    printf("%s;%zu;%zu", "PangoGlyphUnit", sizeof(PangoGlyphUnit), alignof(PangoGlyphUnit));
    printf("%s;%zu;%zu", "PangoGlyphVisAttr", sizeof(PangoGlyphVisAttr), alignof(PangoGlyphVisAttr));
    printf("%s;%zu;%zu", "PangoGravity", sizeof(PangoGravity), alignof(PangoGravity));
    printf("%s;%zu;%zu", "PangoGravityHint", sizeof(PangoGravityHint), alignof(PangoGravityHint));
    printf("%s;%zu;%zu", "PangoIncludedModule", sizeof(PangoIncludedModule), alignof(PangoIncludedModule));
    printf("%s;%zu;%zu", "PangoItem", sizeof(PangoItem), alignof(PangoItem));
    printf("%s;%zu;%zu", "PangoLayoutRun", sizeof(PangoLayoutRun), alignof(PangoLayoutRun));
    printf("%s;%zu;%zu", "PangoMatrix", sizeof(PangoMatrix), alignof(PangoMatrix));
    printf("%s;%zu;%zu", "PangoOverline", sizeof(PangoOverline), alignof(PangoOverline));
    printf("%s;%zu;%zu", "PangoRectangle", sizeof(PangoRectangle), alignof(PangoRectangle));
    printf("%s;%zu;%zu", "PangoRenderPart", sizeof(PangoRenderPart), alignof(PangoRenderPart));
    printf("%s;%zu;%zu", "PangoRenderer", sizeof(PangoRenderer), alignof(PangoRenderer));
    printf("%s;%zu;%zu", "PangoRendererClass", sizeof(PangoRendererClass), alignof(PangoRendererClass));
    printf("%s;%zu;%zu", "PangoScript", sizeof(PangoScript), alignof(PangoScript));
    printf("%s;%zu;%zu", "PangoShapeFlags", sizeof(PangoShapeFlags), alignof(PangoShapeFlags));
    printf("%s;%zu;%zu", "PangoShowFlags", sizeof(PangoShowFlags), alignof(PangoShowFlags));
    printf("%s;%zu;%zu", "PangoStretch", sizeof(PangoStretch), alignof(PangoStretch));
    printf("%s;%zu;%zu", "PangoStyle", sizeof(PangoStyle), alignof(PangoStyle));
    printf("%s;%zu;%zu", "PangoTabAlign", sizeof(PangoTabAlign), alignof(PangoTabAlign));
    printf("%s;%zu;%zu", "PangoUnderline", sizeof(PangoUnderline), alignof(PangoUnderline));
    printf("%s;%zu;%zu", "PangoVariant", sizeof(PangoVariant), alignof(PangoVariant));
    printf("%s;%zu;%zu", "PangoWeight", sizeof(PangoWeight), alignof(PangoWeight));
    printf("%s;%zu;%zu", "PangoWrapMode", sizeof(PangoWrapMode), alignof(PangoWrapMode));
    return 0;
}
