// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>

typedef struct {
    const char *name;
    size_t size;
    size_t alignent;
} Layout;

const Layout LAYOUTS[] = {
};

const Layout *c_layouts(size_t *n) {
    *n = sizeof(LAYOUTS) / sizeof(Layout);
    return LAYOUTS;
}
