// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use gdk_pixbuf_sys::*;
use std::mem::{align_of, size_of};
use std::str;

mod c_abi {
    #[derive(Copy, Clone, Debug, Eq, PartialEq)]
    #[repr(C)]
    pub struct CConstant {
        pub name: *const libc::c_char,
        pub value: *const libc::c_char,
    }

    #[derive(Copy, Clone, Debug, Eq, PartialEq)]
    #[repr(C)]
    pub struct CLayout {
        pub name: *const libc::c_char,
        pub size: usize,
        pub alignment: usize,
    }

    extern "C" {
        pub fn c_constants(n: *mut usize) -> *mut CConstant;
        pub fn c_constants_free(c: *mut CConstant, n: usize);
        pub fn c_layouts(n: *mut usize) -> *const CLayout;
    }
}

fn c_constants() -> Vec<(String, String)> {
    let mut res: Vec<(String, String)> = Vec::new();

    unsafe {
        let mut n = 0;
        let p = c_abi::c_constants(&mut n);
        let constants = std::slice::from_raw_parts(p, n);

        for c in constants {
            let c_name = std::ffi::CStr::from_ptr(c.name);
            let c_value = std::ffi::CStr::from_ptr(c.value);
            res.push((
                c_name.to_str().unwrap().to_owned(),
                c_value.to_str().unwrap().to_owned(),
            ));
        }

        c_abi::c_constants_free(p, n);
    }

    res
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
struct Layout {
    size: usize,
    alignment: usize,
}

fn c_layouts() -> Vec<(String, Layout)> {
    let mut res = Vec::new();

    unsafe {
        let mut n = 0;
        let p = c_abi::c_layouts(&mut n);
        let layouts = std::slice::from_raw_parts(p, n);

        for l in layouts {
            let c_name = std::ffi::CStr::from_ptr(l.name);
            let name = c_name.to_str().unwrap().to_owned();
            let size = l.size;
            let alignment = l.alignment;
            res.push((name, Layout { size, alignment }));
        }
    }

    res
}

#[derive(Copy, Clone, Debug, Default, Eq, PartialEq)]
struct Results {
    /// Number of successfully completed tests.
    passed: usize,
    /// Total number of failed tests (including those that failed to compile).
    failed: usize,
}

impl Results {
    fn record_passed(&mut self) {
        self.passed += 1;
    }
    fn record_failed(&mut self) {
        self.failed += 1;
    }
    fn summary(&self) -> String {
        format!("{} passed; {} failed", self.passed, self.failed)
    }
    fn expect_total_success(&self) {
        if self.failed == 0 {
            println!("OK: {}", self.summary());
        } else {
            panic!("FAILED: {}", self.summary());
        };
    }
}

#[test]
fn cross_validate_constants_with_c() {
    let mut results = Results::default();

    for ((rust_name, rust_value), (c_name, c_value)) in
        RUST_CONSTANTS.iter().zip(c_constants().iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {:?}\nC:    {:?}", rust_name, c_name,);
            continue;
        }

        if rust_value != c_value {
            results.record_failed();
            eprintln!(
                "Constant value mismatch for {}\nRust: {:?}\nC:    {:?}",
                rust_name, rust_value, &c_value
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

#[test]
fn cross_validate_layout_with_c() {
    let mut results = Results::default();

    for ((rust_name, rust_layout), (c_name, c_layout)) in
        RUST_LAYOUTS.iter().zip(c_layouts().iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {:?}\nC:    {:?}", rust_name, c_name,);
            continue;
        }

        if rust_layout != c_layout {
            results.record_failed();
            eprintln!(
                "Layout mismatch for {}\nRust: {:?}\nC:    {:?}",
                rust_name, rust_layout, &c_layout
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

const RUST_LAYOUTS: &[(&str, Layout)] = &[
    (
        "GdkColorspace",
        Layout {
            size: size_of::<GdkColorspace>(),
            alignment: align_of::<GdkColorspace>(),
        },
    ),
    (
        "GdkInterpType",
        Layout {
            size: size_of::<GdkInterpType>(),
            alignment: align_of::<GdkInterpType>(),
        },
    ),
    (
        "GdkPixbufAlphaMode",
        Layout {
            size: size_of::<GdkPixbufAlphaMode>(),
            alignment: align_of::<GdkPixbufAlphaMode>(),
        },
    ),
    (
        "GdkPixbufAnimation",
        Layout {
            size: size_of::<GdkPixbufAnimation>(),
            alignment: align_of::<GdkPixbufAnimation>(),
        },
    ),
    (
        "GdkPixbufAnimationClass",
        Layout {
            size: size_of::<GdkPixbufAnimationClass>(),
            alignment: align_of::<GdkPixbufAnimationClass>(),
        },
    ),
    (
        "GdkPixbufAnimationIter",
        Layout {
            size: size_of::<GdkPixbufAnimationIter>(),
            alignment: align_of::<GdkPixbufAnimationIter>(),
        },
    ),
    (
        "GdkPixbufAnimationIterClass",
        Layout {
            size: size_of::<GdkPixbufAnimationIterClass>(),
            alignment: align_of::<GdkPixbufAnimationIterClass>(),
        },
    ),
    (
        "GdkPixbufError",
        Layout {
            size: size_of::<GdkPixbufError>(),
            alignment: align_of::<GdkPixbufError>(),
        },
    ),
    (
        "GdkPixbufFormat",
        Layout {
            size: size_of::<GdkPixbufFormat>(),
            alignment: align_of::<GdkPixbufFormat>(),
        },
    ),
    (
        "GdkPixbufFormatFlags",
        Layout {
            size: size_of::<GdkPixbufFormatFlags>(),
            alignment: align_of::<GdkPixbufFormatFlags>(),
        },
    ),
    (
        "GdkPixbufLoader",
        Layout {
            size: size_of::<GdkPixbufLoader>(),
            alignment: align_of::<GdkPixbufLoader>(),
        },
    ),
    (
        "GdkPixbufLoaderClass",
        Layout {
            size: size_of::<GdkPixbufLoaderClass>(),
            alignment: align_of::<GdkPixbufLoaderClass>(),
        },
    ),
    (
        "GdkPixbufModule",
        Layout {
            size: size_of::<GdkPixbufModule>(),
            alignment: align_of::<GdkPixbufModule>(),
        },
    ),
    (
        "GdkPixbufModulePattern",
        Layout {
            size: size_of::<GdkPixbufModulePattern>(),
            alignment: align_of::<GdkPixbufModulePattern>(),
        },
    ),
    (
        "GdkPixbufRotation",
        Layout {
            size: size_of::<GdkPixbufRotation>(),
            alignment: align_of::<GdkPixbufRotation>(),
        },
    ),
];

const RUST_CONSTANTS: &[(&str, &str)] = &[
    ("(gint) GDK_COLORSPACE_RGB", "0"),
    ("(gint) GDK_INTERP_BILINEAR", "2"),
    ("(gint) GDK_INTERP_HYPER", "3"),
    ("(gint) GDK_INTERP_NEAREST", "0"),
    ("(gint) GDK_INTERP_TILES", "1"),
    ("(gint) GDK_PIXBUF_ALPHA_BILEVEL", "0"),
    ("(gint) GDK_PIXBUF_ALPHA_FULL", "1"),
    ("(gint) GDK_PIXBUF_ERROR_BAD_OPTION", "2"),
    ("(gint) GDK_PIXBUF_ERROR_CORRUPT_IMAGE", "0"),
    ("(gint) GDK_PIXBUF_ERROR_FAILED", "5"),
    ("(gint) GDK_PIXBUF_ERROR_INCOMPLETE_ANIMATION", "6"),
    ("(gint) GDK_PIXBUF_ERROR_INSUFFICIENT_MEMORY", "1"),
    ("(gint) GDK_PIXBUF_ERROR_UNKNOWN_TYPE", "3"),
    ("(gint) GDK_PIXBUF_ERROR_UNSUPPORTED_OPERATION", "4"),
    ("(guint) GDK_PIXBUF_FORMAT_SCALABLE", "2"),
    ("(guint) GDK_PIXBUF_FORMAT_THREADSAFE", "4"),
    ("(guint) GDK_PIXBUF_FORMAT_WRITABLE", "1"),
    ("(gint) GDK_PIXBUF_ROTATE_CLOCKWISE", "270"),
    ("(gint) GDK_PIXBUF_ROTATE_COUNTERCLOCKWISE", "90"),
    ("(gint) GDK_PIXBUF_ROTATE_NONE", "0"),
    ("(gint) GDK_PIXBUF_ROTATE_UPSIDEDOWN", "180"),
];
