// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>
int main() {
    printf("%s;%zu;%zu", "GdkColorspace", sizeof(GdkColorspace), alignof(GdkColorspace));
    printf("%s;%zu;%zu", "GdkInterpType", sizeof(GdkInterpType), alignof(GdkInterpType));
    printf("%s;%zu;%zu", "GdkPixbufAlphaMode", sizeof(GdkPixbufAlphaMode), alignof(GdkPixbufAlphaMode));
    printf("%s;%zu;%zu", "GdkPixbufAnimation", sizeof(GdkPixbufAnimation), alignof(GdkPixbufAnimation));
    printf("%s;%zu;%zu", "GdkPixbufAnimationClass", sizeof(GdkPixbufAnimationClass), alignof(GdkPixbufAnimationClass));
    printf("%s;%zu;%zu", "GdkPixbufAnimationIter", sizeof(GdkPixbufAnimationIter), alignof(GdkPixbufAnimationIter));
    printf("%s;%zu;%zu", "GdkPixbufAnimationIterClass", sizeof(GdkPixbufAnimationIterClass), alignof(GdkPixbufAnimationIterClass));
    printf("%s;%zu;%zu", "GdkPixbufError", sizeof(GdkPixbufError), alignof(GdkPixbufError));
    printf("%s;%zu;%zu", "GdkPixbufFormat", sizeof(GdkPixbufFormat), alignof(GdkPixbufFormat));
    printf("%s;%zu;%zu", "GdkPixbufFormatFlags", sizeof(GdkPixbufFormatFlags), alignof(GdkPixbufFormatFlags));
    printf("%s;%zu;%zu", "GdkPixbufLoader", sizeof(GdkPixbufLoader), alignof(GdkPixbufLoader));
    printf("%s;%zu;%zu", "GdkPixbufLoaderClass", sizeof(GdkPixbufLoaderClass), alignof(GdkPixbufLoaderClass));
    printf("%s;%zu;%zu", "GdkPixbufModule", sizeof(GdkPixbufModule), alignof(GdkPixbufModule));
    printf("%s;%zu;%zu", "GdkPixbufModulePattern", sizeof(GdkPixbufModulePattern), alignof(GdkPixbufModulePattern));
    printf("%s;%zu;%zu", "GdkPixbufRotation", sizeof(GdkPixbufRotation), alignof(GdkPixbufRotation));
    return 0;
}
