// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>

typedef struct {
    const char *name;
    size_t size;
    size_t alignent;
} Layout;

const Layout LAYOUTS[] = {
    { "AtkActionIface", sizeof(AtkActionIface), alignof(AtkActionIface) },
    { "AtkAttribute", sizeof(AtkAttribute), alignof(AtkAttribute) },
    { "AtkAttributeSet", sizeof(AtkAttributeSet), alignof(AtkAttributeSet) },
    { "AtkComponentIface", sizeof(AtkComponentIface), alignof(AtkComponentIface) },
    { "AtkCoordType", sizeof(AtkCoordType), alignof(AtkCoordType) },
    { "AtkDocumentIface", sizeof(AtkDocumentIface), alignof(AtkDocumentIface) },
    { "AtkEditableTextIface", sizeof(AtkEditableTextIface), alignof(AtkEditableTextIface) },
    { "AtkGObjectAccessible", sizeof(AtkGObjectAccessible), alignof(AtkGObjectAccessible) },
    { "AtkGObjectAccessibleClass", sizeof(AtkGObjectAccessibleClass), alignof(AtkGObjectAccessibleClass) },
    { "AtkHyperlink", sizeof(AtkHyperlink), alignof(AtkHyperlink) },
    { "AtkHyperlinkClass", sizeof(AtkHyperlinkClass), alignof(AtkHyperlinkClass) },
    { "AtkHyperlinkImplIface", sizeof(AtkHyperlinkImplIface), alignof(AtkHyperlinkImplIface) },
    { "AtkHyperlinkStateFlags", sizeof(AtkHyperlinkStateFlags), alignof(AtkHyperlinkStateFlags) },
    { "AtkHypertextIface", sizeof(AtkHypertextIface), alignof(AtkHypertextIface) },
    { "AtkImageIface", sizeof(AtkImageIface), alignof(AtkImageIface) },
    { "AtkKeyEventStruct", sizeof(AtkKeyEventStruct), alignof(AtkKeyEventStruct) },
    { "AtkKeyEventType", sizeof(AtkKeyEventType), alignof(AtkKeyEventType) },
    { "AtkLayer", sizeof(AtkLayer), alignof(AtkLayer) },
    { "AtkMisc", sizeof(AtkMisc), alignof(AtkMisc) },
    { "AtkMiscClass", sizeof(AtkMiscClass), alignof(AtkMiscClass) },
    { "AtkNoOpObject", sizeof(AtkNoOpObject), alignof(AtkNoOpObject) },
    { "AtkNoOpObjectClass", sizeof(AtkNoOpObjectClass), alignof(AtkNoOpObjectClass) },
    { "AtkNoOpObjectFactory", sizeof(AtkNoOpObjectFactory), alignof(AtkNoOpObjectFactory) },
    { "AtkNoOpObjectFactoryClass", sizeof(AtkNoOpObjectFactoryClass), alignof(AtkNoOpObjectFactoryClass) },
    { "AtkObject", sizeof(AtkObject), alignof(AtkObject) },
    { "AtkObjectClass", sizeof(AtkObjectClass), alignof(AtkObjectClass) },
    { "AtkObjectFactory", sizeof(AtkObjectFactory), alignof(AtkObjectFactory) },
    { "AtkObjectFactoryClass", sizeof(AtkObjectFactoryClass), alignof(AtkObjectFactoryClass) },
    { "AtkPlug", sizeof(AtkPlug), alignof(AtkPlug) },
    { "AtkPlugClass", sizeof(AtkPlugClass), alignof(AtkPlugClass) },
    { "AtkPropertyValues", sizeof(AtkPropertyValues), alignof(AtkPropertyValues) },
    { "AtkRectangle", sizeof(AtkRectangle), alignof(AtkRectangle) },
    { "AtkRegistry", sizeof(AtkRegistry), alignof(AtkRegistry) },
    { "AtkRegistryClass", sizeof(AtkRegistryClass), alignof(AtkRegistryClass) },
    { "AtkRelation", sizeof(AtkRelation), alignof(AtkRelation) },
    { "AtkRelationClass", sizeof(AtkRelationClass), alignof(AtkRelationClass) },
    { "AtkRelationSet", sizeof(AtkRelationSet), alignof(AtkRelationSet) },
    { "AtkRelationSetClass", sizeof(AtkRelationSetClass), alignof(AtkRelationSetClass) },
    { "AtkRelationType", sizeof(AtkRelationType), alignof(AtkRelationType) },
    { "AtkRole", sizeof(AtkRole), alignof(AtkRole) },
    { "AtkScrollType", sizeof(AtkScrollType), alignof(AtkScrollType) },
    { "AtkSelectionIface", sizeof(AtkSelectionIface), alignof(AtkSelectionIface) },
    { "AtkSocket", sizeof(AtkSocket), alignof(AtkSocket) },
    { "AtkSocketClass", sizeof(AtkSocketClass), alignof(AtkSocketClass) },
    { "AtkState", sizeof(AtkState), alignof(AtkState) },
    { "AtkStateSet", sizeof(AtkStateSet), alignof(AtkStateSet) },
    { "AtkStateSetClass", sizeof(AtkStateSetClass), alignof(AtkStateSetClass) },
    { "AtkStateType", sizeof(AtkStateType), alignof(AtkStateType) },
    { "AtkStreamableContentIface", sizeof(AtkStreamableContentIface), alignof(AtkStreamableContentIface) },
    { "AtkTableCellIface", sizeof(AtkTableCellIface), alignof(AtkTableCellIface) },
    { "AtkTableIface", sizeof(AtkTableIface), alignof(AtkTableIface) },
    { "AtkTextAttribute", sizeof(AtkTextAttribute), alignof(AtkTextAttribute) },
    { "AtkTextBoundary", sizeof(AtkTextBoundary), alignof(AtkTextBoundary) },
    { "AtkTextClipType", sizeof(AtkTextClipType), alignof(AtkTextClipType) },
    { "AtkTextGranularity", sizeof(AtkTextGranularity), alignof(AtkTextGranularity) },
    { "AtkTextIface", sizeof(AtkTextIface), alignof(AtkTextIface) },
    { "AtkTextRange", sizeof(AtkTextRange), alignof(AtkTextRange) },
    { "AtkTextRectangle", sizeof(AtkTextRectangle), alignof(AtkTextRectangle) },
    { "AtkUtil", sizeof(AtkUtil), alignof(AtkUtil) },
    { "AtkUtilClass", sizeof(AtkUtilClass), alignof(AtkUtilClass) },
    { "AtkValueIface", sizeof(AtkValueIface), alignof(AtkValueIface) },
    { "AtkValueType", sizeof(AtkValueType), alignof(AtkValueType) },
    { "AtkWindowIface", sizeof(AtkWindowIface), alignof(AtkWindowIface) }
};

const Layout *c_layouts(size_t *n) {
    *n = sizeof(LAYOUTS) / sizeof(Layout);
    return LAYOUTS;
}
