// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>

typedef struct {
    const char *name;
    size_t size;
    size_t alignent;
} Layout;

const Layout LAYOUTS[] = {
    { "GBindingFlags", sizeof(GBindingFlags), alignof(GBindingFlags) },
    { "GClosureNotifyData", sizeof(GClosureNotifyData), alignof(GClosureNotifyData) },
    { "GConnectFlags", sizeof(GConnectFlags), alignof(GConnectFlags) },
    { "GEnumClass", sizeof(GEnumClass), alignof(GEnumClass) },
    { "GEnumValue", sizeof(GEnumValue), alignof(GEnumValue) },
    { "GFlagsClass", sizeof(GFlagsClass), alignof(GFlagsClass) },
    { "GFlagsValue", sizeof(GFlagsValue), alignof(GFlagsValue) },
    { "GInitiallyUnowned", sizeof(GInitiallyUnowned), alignof(GInitiallyUnowned) },
    { "GInitiallyUnownedClass", sizeof(GInitiallyUnownedClass), alignof(GInitiallyUnownedClass) },
    { "GInterfaceInfo", sizeof(GInterfaceInfo), alignof(GInterfaceInfo) },
    { "GObject", sizeof(GObject), alignof(GObject) },
    { "GObjectClass", sizeof(GObjectClass), alignof(GObjectClass) },
    { "GObjectConstructParam", sizeof(GObjectConstructParam), alignof(GObjectConstructParam) },
    { "GParamFlags", sizeof(GParamFlags), alignof(GParamFlags) },
    { "GParamSpec", sizeof(GParamSpec), alignof(GParamSpec) },
    { "GParamSpecBoolean", sizeof(GParamSpecBoolean), alignof(GParamSpecBoolean) },
    { "GParamSpecBoxed", sizeof(GParamSpecBoxed), alignof(GParamSpecBoxed) },
    { "GParamSpecChar", sizeof(GParamSpecChar), alignof(GParamSpecChar) },
    { "GParamSpecClass", sizeof(GParamSpecClass), alignof(GParamSpecClass) },
    { "GParamSpecDouble", sizeof(GParamSpecDouble), alignof(GParamSpecDouble) },
    { "GParamSpecEnum", sizeof(GParamSpecEnum), alignof(GParamSpecEnum) },
    { "GParamSpecFlags", sizeof(GParamSpecFlags), alignof(GParamSpecFlags) },
    { "GParamSpecFloat", sizeof(GParamSpecFloat), alignof(GParamSpecFloat) },
    { "GParamSpecGType", sizeof(GParamSpecGType), alignof(GParamSpecGType) },
    { "GParamSpecInt", sizeof(GParamSpecInt), alignof(GParamSpecInt) },
    { "GParamSpecInt64", sizeof(GParamSpecInt64), alignof(GParamSpecInt64) },
    { "GParamSpecLong", sizeof(GParamSpecLong), alignof(GParamSpecLong) },
    { "GParamSpecObject", sizeof(GParamSpecObject), alignof(GParamSpecObject) },
    { "GParamSpecOverride", sizeof(GParamSpecOverride), alignof(GParamSpecOverride) },
    { "GParamSpecParam", sizeof(GParamSpecParam), alignof(GParamSpecParam) },
    { "GParamSpecPointer", sizeof(GParamSpecPointer), alignof(GParamSpecPointer) },
    { "GParamSpecTypeInfo", sizeof(GParamSpecTypeInfo), alignof(GParamSpecTypeInfo) },
    { "GParamSpecUChar", sizeof(GParamSpecUChar), alignof(GParamSpecUChar) },
    { "GParamSpecUInt", sizeof(GParamSpecUInt), alignof(GParamSpecUInt) },
    { "GParamSpecUInt64", sizeof(GParamSpecUInt64), alignof(GParamSpecUInt64) },
    { "GParamSpecULong", sizeof(GParamSpecULong), alignof(GParamSpecULong) },
    { "GParamSpecUnichar", sizeof(GParamSpecUnichar), alignof(GParamSpecUnichar) },
    { "GParamSpecValueArray", sizeof(GParamSpecValueArray), alignof(GParamSpecValueArray) },
    { "GParamSpecVariant", sizeof(GParamSpecVariant), alignof(GParamSpecVariant) },
    { "GParameter", sizeof(GParameter), alignof(GParameter) },
    { "GSignalCMarshaller", sizeof(GSignalCMarshaller), alignof(GSignalCMarshaller) },
    { "GSignalFlags", sizeof(GSignalFlags), alignof(GSignalFlags) },
    { "GSignalInvocationHint", sizeof(GSignalInvocationHint), alignof(GSignalInvocationHint) },
    { "GSignalMatchType", sizeof(GSignalMatchType), alignof(GSignalMatchType) },
    { "GSignalQuery", sizeof(GSignalQuery), alignof(GSignalQuery) },
    { "GTypeClass", sizeof(GTypeClass), alignof(GTypeClass) },
    { "GTypeDebugFlags", sizeof(GTypeDebugFlags), alignof(GTypeDebugFlags) },
    { "GTypeFlags", sizeof(GTypeFlags), alignof(GTypeFlags) },
    { "GTypeFundamentalFlags", sizeof(GTypeFundamentalFlags), alignof(GTypeFundamentalFlags) },
    { "GTypeFundamentalInfo", sizeof(GTypeFundamentalInfo), alignof(GTypeFundamentalInfo) },
    { "GTypeInfo", sizeof(GTypeInfo), alignof(GTypeInfo) },
    { "GTypeInstance", sizeof(GTypeInstance), alignof(GTypeInstance) },
    { "GTypeInterface", sizeof(GTypeInterface), alignof(GTypeInterface) },
    { "GTypeModule", sizeof(GTypeModule), alignof(GTypeModule) },
    { "GTypeModuleClass", sizeof(GTypeModuleClass), alignof(GTypeModuleClass) },
    { "GTypePluginClass", sizeof(GTypePluginClass), alignof(GTypePluginClass) },
    { "GTypeQuery", sizeof(GTypeQuery), alignof(GTypeQuery) },
    { "GTypeValueTable", sizeof(GTypeValueTable), alignof(GTypeValueTable) },
    { "GValue", sizeof(GValue), alignof(GValue) },
    { "GValueArray", sizeof(GValueArray), alignof(GValueArray) },
    { "GWeakRef", sizeof(GWeakRef), alignof(GWeakRef) }
};

const Layout *c_layouts(size_t *n) {
    *n = sizeof(LAYOUTS) / sizeof(Layout);
    return LAYOUTS;
}
