on:
  push:
    branches: [winci]
  pull_request:

name: CI

jobs:

  build-win:
    name: build windows
    runs-on: windows-latest
    env:
      gvsbuildref: 3c45d961a5ab23f8ece72f6a5470b8ec87081b5e

    steps:

      - uses: actions/checkout@v2

      - name: gvsbuild cache
        uses: actions/cache@v2
        id: gvsbuildcache
        with:
          path: C:\gtk-build\**
          key: ${{ runner.os }}-gvsbuild-$${{ env.gvsbuildref }}

      - name: checkout gvsbuild
        if: steps.gvsbuildcache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: wingtk/gvsbuild
          ref: $${{ env.gvsbuildref }}
          path: gvsbuild

      # Remove the preinstalled git, it causes errors related to cygwin.
      # Note this need to happen after we checked out the projects.
      - name: remove git
        if: steps.gvsbuildcache.outputs.cache-hit != 'true'
        run: rmdir "C:\Program Files\Git\usr\bin" /s /q
        shell: cmd

      - name: gvsbuild
        if: steps.gvsbuildcache.outputs.cache-hit != 'true'
        working-directory: gvsbuild
        run: python .\build.py build -p=x64 --vs-ver=16 --msys-dir=C:\msys64 gtk3

      - name: setup env
        run:  echo "C:\gtk-build\gtk\x64\release\bin" >> $GITHUB_PATH

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: atk test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path atk/Cargo.toml --features "v2_34"

#
#      - name: atk-sys test
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --manifest-path atk/sys/Cargo.toml --features "v2_34"
#
#      - name: atk build
#        uses: actions-rs/cargo@v1
#        with:
#          command: build
#          args: --manifest-path atk/sys/Cargo.toml --features "v2_34"

