on:
  push:
    branches: [winci]
  pull_request:

name: CI

jobs:

  build-win:
    name: build windows
    runs-on: windows-latest

    steps:

      - name: Checkout gvsbuild
        uses: actions/checkout@v2
        with:
          repository: wingtk/gvsbuild
          path: gtk-build\github\gvsbuild

      - name: gvsbuild
        run: python .\build.py build -p=x64 --vs-ver=16 --msys-dir=C:\mingw64 gtk3
        working-directory: gtk-build\github\gvsbuild

      - name: Setup env
        run: echo "C:\gtk-build\gtk\x64\release\bin" >> $GITHUB_PATH

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - uses: actions/checkout@v2

      - name: atk test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path atk/Cargo.toml --features "v2_34"

#
#      - name: atk-sys test
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --manifest-path atk/sys/Cargo.toml --features "v2_34"
#
#      - name: atk build
#        uses: actions-rs/cargo@v1
#        with:
#          command: build
#          args: --manifest-path atk/sys/Cargo.toml --features "v2_34"

