on:
  push:
    branches: [winci]
  pull_request:

name: CI

jobs:

  build-win:
    name: build windows
    runs-on: windows-latest
    env:
      # git revision of gvsbuild we use for the GTK dependendency
      gvsbuildref: 3c45d961a5ab23f8ece72f6a5470b8ec87081b5e

      # bump this number if you want to force a rebuild of gvsbuild
      gvsbuildupdate: 1

    steps:

      - uses: actions/checkout@v2

      # this is needed for the cache restore to work
      - name: (GTK binaries) create dir
        run: mkdir C:\gtk-build\gtk\x64\release

      - name: (GTK binaries) get from cache
        uses: actions/cache@v2
        id: cache
        with:
          path: C:\gtk-build\gtk\x64\release\**
          key: gvsbuild-${{ env.gvsbuildupdate }}-${{ env.gvsbuildref }}

      - name: (GTK binaries) checkout gvsbuild
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: wingtk/gvsbuild
          ref: ${{ env.gvsbuildref }}
          path: gvsbuild

      # Remove the preinstalled git, it causes errors related to cygwin.
      # Note this needs to happen after we checked out the projects.
      - name: (GTK binaries) remove git binary
        if: steps.cache.outputs.cache-hit != 'true'
        run: rmdir "C:\Program Files\Git\usr\bin" /s /q
        shell: cmd

      - name: (GTK binaries) run gvsbuild
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: gvsbuild
        run: python .\build.py build -p=x64 --vs-ver=16 --msys-dir=C:\msys64 gtk3

      - name: Setup env
        run:  |
          echo "PKG_CONFIG=C:\gtk-build\gtk\x64\release\bin\pkgconf.exe" >> $GITHUB_ENV
          echo "C:\gtk-build\gtk\x64\release\bin" >> $GITHUB_PATH

      - name: Test
        run:  |
          set
          C:\gtk-build\gtk\x64\release\bin\pkgconf.exe --libs --cflags glib-2.0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: atk test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path atk/Cargo.toml --features "v2_34"
          env:
            GTK_LIB_DIR=C:\gtk-build\gtk\x64\release\bin\

#
#      - name: atk-sys test
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --manifest-path atk/sys/Cargo.toml --features "v2_34"
#
#      - name: atk build
#        uses: actions-rs/cargo@v1
#        with:
#          command: build
#          args: --manifest-path atk/sys/Cargo.toml --features "v2_34"

