on:
  push:
    branches: [winci]
  pull_request:

name: CI

jobs:

  build-win:
    name: build windows msys2
    runs-on: windows-latest
      
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: base-devel git mingw-w64-x86_64-gtk3

      - name: show env
        run: |
          env | sort
          cd /
          find / "*.pc"
          find / "*glib*"
