on:
  push:
    branches: [winci]
  pull_request:

name: CI

jobs:

  build-win:
    name: build windows
    runs-on: windows-latest
    env:
      # git revision of gvsbuild we use for the GTK dependendency
      gvsbuildref: 3c45d961a5ab23f8ece72f6a5470b8ec87081b5e

      # bump this number if you want to force a rebuild of gvsbuild
      gvsbuildupdate: 1

    strategy:
      matrix:
        # For now we turn off almost all sys tests, since they fail the ABI check
        projects:
          - { name: "atk", test: true, test-sys: false, features: "v2_34" }
          # Turn test off: hangs in context::tests::clip_rectange has been running for over 60 seconds
          - { name: "cairo", test: false, test-sys: true, features: "png,pdf,svg,ps,use_glib,v1_16,freetype,script,win32-surface" }
          - { name: "gdk", test: true, test-sys: false, features: "v3_24" }
          - { name: "gdk-pixbuf", test: true, test-sys: false, features: "v2_40" }
          - { name: "gdkx11", test: true, test-sys: false, features: "v3_24" }
          - { name: "gio", test: true, test-sys: false, features: "v2_66" }
          # Turn test off: fails in translate::tests::test_paths stdout: "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\.tmpMhxy2C" vs "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\.tmpMhxy2C"
          - { name: "glib", test: false, test-sys: false, features: "v2_66" }
          - { name: "graphene", test: true, test-sys: false, features: "v1_10" }
          - { name: "gtk", test: true, test-sys: false, features: "v3_24_9" }
          - { name: "pango", test: true, test-sys: false, features: "v1_46" }
          - { name: "pangocairo", test: true, test-sys: false, features: "" }

    steps:

      - uses: actions/checkout@v2

      # this is needed for the cache restore to work
      - name: (GTK binaries) create dir
        run: mkdir C:\gtk-build\gtk\x64\release

      - name: (GTK binaries) get from cache
        uses: actions/cache@v2
        id: cache
        with:
          path: C:\gtk-build\gtk\x64\release\**
          key: gvsbuild-${{ env.gvsbuildupdate }}-${{ env.gvsbuildref }}

      - name: (GTK binaries) checkout gvsbuild
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: wingtk/gvsbuild
          ref: ${{ env.gvsbuildref }}
          path: gvsbuild

      # Remove the preinstalled git, it causes errors related to cygwin.
      # Note this needs to happen after we checked out the projects.
      - name: (GTK binaries) remove git binary
        if: steps.cache.outputs.cache-hit != 'true'
        run: rmdir "C:\Program Files\Git\usr\bin" /s /q
        shell: cmd

      - name: (GTK binaries) run gvsbuild
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: gvsbuild
        run: python .\build.py build -p=x64 --vs-ver=16 --msys-dir=C:\msys64 gtk3

      - name: Setup env
        run: |
          echo "PKG_CONFIG=C:\gtk-build\gtk\x64\release\bin\pkgconf.exe" >> $GITHUB_ENV
          echo "C:\gtk-build\gtk\x64\release\bin" >> $GITHUB_PATH
        shell: bash

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      # Crates

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ matrix.projects.name }}/Cargo.toml --features ${{ matrix.projects.features }}
        if: matrix.projects.test

      - name: test sys
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ matrix.projects.name }}/sys/Cargo.toml --features ${{ matrix.projects.features }}
        if: matrix.projects.test-sys

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ${{ matrix.projects.name }}/Cargo.toml --features ${{ matrix.projects.features }}

      # Examples

      - name: examples
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path examples/Cargo.toml --bins --examples --all-features

