on:
  push:
    branches: [winci]
  pull_request:

name: CI

jobs:

  build-win:
    name: build windows msys2
    runs-on: windows-latest
      
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: base-devel mingw-w64-x86_64-pkg-config mingw-w64-x86_64-gtk3 

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-pc-windows-gnu
          override: true

      - uses: actions/checkout@v2
          
      - name: atk test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path atk/Cargo.toml --features "v2_34"
        env:
          GTK_LIB_DIR: C:\mingw64\bin
          PKG_CONFIG_ALLOW_CROSS: 1
          PKG_CONFIG: C:\mingw64\bin\pkg-config.exe
          PKG_CONFIG_PATH: C:\mingw64\share\pkgconfig;C:\mingw64\lib\pkgconfig
#
#      - name: atk-sys test
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --manifest-path atk/sys/Cargo.toml --features "v2_34"
#
#      - name: atk build
#        uses: actions-rs/cargo@v1
#        with:
#          command: build
#          args: --manifest-path atk/sys/Cargo.toml --features "v2_34"

