on:
  push:
    branches: [winci]
  pull_request:

name: CI

jobs:

  build-win:
    name: build windows
    runs-on: windows-latest
    env:
      # git revision of gvsbuild we use for the GTK dependendency
      gvsbuildref: 3c45d961a5ab23f8ece72f6a5470b8ec87081b5e

      # bump this number if you want to force a rebuild of gvsbuild
      gvsbuildupdate: 1

    steps:

      - uses: actions/checkout@v2

      # this is needed for the cache restore to work
      - name: (GTK binaries) create dir
        run: mkdir C:\gtk-build\gtk\x64\release

      - name: (GTK binaries) get from cache
        uses: actions/cache@v2
        id: cache
        with:
          path: C:\gtk-build\gtk\x64\release\**
          key: gvsbuild-${{ env.gvsbuildupdate }}-${{ env.gvsbuildref }}

      - name: (GTK binaries) checkout gvsbuild
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: wingtk/gvsbuild
          ref: ${{ env.gvsbuildref }}
          path: gvsbuild

      # Remove the preinstalled git, it causes errors related to cygwin.
      # Note this needs to happen after we checked out the projects.
      - name: (GTK binaries) remove git binary
        if: steps.cache.outputs.cache-hit != 'true'
        run: rmdir "C:\Program Files\Git\usr\bin" /s /q
        shell: cmd

      - name: (GTK binaries) run gvsbuild
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: gvsbuild
        run: python .\build.py build -p=x64 --vs-ver=16 --msys-dir=C:\msys64 gtk3

      - name: Setup env
        run: |
          echo PKG_CONFIG=C:\gtk-build\gtk\x64\release\bin\pkgconf.exe >> %GITHUB_ENV%
          echo C:\gtk-build\gtk\x64\release\bin >> %GITHUB_ENV%
        shell: cmd

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      # ATK

      - name: atk test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path atk/Cargo.toml --features "v2_34"

      # FAILS: thread 'cross_validate_constants_with_c' panicked at 'configured compiler: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', atk\sys\tests\abi.rs:131:30
      #- name: atk-sys test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --manifest-path atk/sys/Cargo.toml --features "v2_34"

      - name: atk build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path atk/Cargo.toml --features "v2_34"

      # Cairo

      # HANGS: test context::tests::clip_rectange ... test context::tests::clip_rectange has been running for over 60 seconds
      #- name: cairo test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --manifest-path cairo/Cargo.toml --features "png,pdf,svg,ps,use_glib,v1_16,freetype,script,win32-surface"

      - name: cairo-sys test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path cairo/sys/Cargo.toml --features "png,pdf,svg,ps,use_glib,v1_16,freetype,script,win32-surface"

      - name: cairo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path cairo/Cargo.toml --features "png,pdf,svg,ps,use_glib,v1_16,freetype,script,win32-surface"

      # GDK

      - name: gdk test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path gdk/Cargo.toml --features v3_24

      # FAILS: abi check
      # - name: gdk-sys test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --manifest-path gdk/sys/Cargo.toml --features v3_24

      - name: gdk build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path gdk/Cargo.toml --features v3_24

      # gdk-pixbuf

      - name: gdk-pixbuf test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path gdk-pixbuf/Cargo.toml --features "v2_40"

      # FAILS: abi check
      #- name: gdk-pixbuf-sys test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --manifest-path gdk-pixbuf/sys/Cargo.toml --features "v2_40"

      - name: gdk-pixbuf build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path gdk-pixbuf/Cargo.toml --features "v2_40"

      # gio

      - name: gio test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path gio/Cargo.toml --features "v2_66" -- --nocapture

      # FAILS: abi check
      #- name: gio-sys test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --manifest-path gio/sys/Cargo.toml --features "v2_66"

      - name: gio build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path gio/Cargo.toml --features "v2_66"

      # glib

      # FAILS in translate::tests::test_paths stdout: "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\.tmpMhxy2C" vs "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\.tmpMhxy2C"
      #- name: glib test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --manifest-path glib/Cargo.toml --features "v2_66"

      # FAILS: abi check
      #- name: glib-sys test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --manifest-path glib/sys/Cargo.toml --features "v2_66"

      - name: glib build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path glib/Cargo.toml --features "v2_66"

      # glib-macros

      - name: glib-macros test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path glib-macros/Cargo.toml

      - name: glib-macros build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path glib-macros/Cargo.toml

      # pango

      - name: pango test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path pango/Cargo.toml --features "v1_46"

      #- name: pango-sys test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --manifest-path pango/sys/Cargo.toml --features "v1_46"

      - name: pango build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path pango/Cargo.toml --features "v1_46"

      # pangocairo

      - name: pangocairo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path pangocairo/Cargo.toml

      #- name: pangocairo-sys test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --manifest-path pangocairo/sys/Cargo.toml

      - name: pangocairo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path pangocairo/Cargo.toml

      # GTK

      - name: gtk test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path gtk/Cargo.toml --features "v3_24_9"

      #- name: gtk-sys test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --manifest-path gtk/sys/Cargo.toml --features "v3_24_9"

      - name: gtk build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path gtk/Cargo.toml --features "v3_24_9"

      # Examples

      - name: examples
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path examples/Cargo.toml --bins --examples --all-features

