on:
  push:
    branches: [winci]
  pull_request:

name: CI

jobs:

  build-win:
    name: build windows
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v2

      - name: Checkout gvsbuild
        uses: actions/checkout@v2
        with:
          repository: wingtk/gvsbuild
          # ref: specify ref so that we know which version of the deps it is?
          path: gvsbuild

      - name: gvsbuild cache
        uses: actions/cache@v2
        id: gvsbuildcache
        with:
          path: C:\gtk-build\**
          # how to define a unique key? maybe we can specify the ref of the gvsbuild repo
          key: ${{ runner.os }}-gvsbuild-xxxx

      # Remove the preinstalled git, it causes errors related to cygwin.
      # Note this need to happen after we checked out the projects.
      - name: remove git
        if: steps.gvsbuildcache.outputs.cache-hit != 'true'
        run: rmdir "C:\Program Files\Git\usr\bin" /s /q
        shell: cmd

      - name: gvsbuild
        working-directory: gvsbuild
        if: steps.gvsbuildcache.outputs.cache-hit != 'true'
        run: python .\build.py build -p=x64 --vs-ver=16 --msys-dir=C:\msys64 gtk3

#      - name: move gtk files
#        run: xcopy /e /i gtk-build\gtk C:\gtk

      - name: setup env
        run:  echo "C:\gtk-build\gtk\x64\release\bin" >> $GITHUB_PATH

#     - name: Copy gtk
#      if: runner.os == 'windows' && steps.cache.outputs.cache-hit == 'true'
#      run: xcopy /e /i release C:\gtk-build\gtk\x64\release
#      shell: cmd
#    - name: Windows dependencies (copy gvsbuild)
#      if: runner.os == 'windows' && steps.cache.outputs.cache-hit != 'true'

#      - name: Setup env
        #echo "C:\gtk-build\gtk\x64\release\bin" >> $GITHUB_PATH

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: atk test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path atk/Cargo.toml --features "v2_34"

#
#      - name: atk-sys test
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --manifest-path atk/sys/Cargo.toml --features "v2_34"
#
#      - name: atk build
#        uses: actions-rs/cargo@v1
#        with:
#          command: build
#          args: --manifest-path atk/sys/Cargo.toml --features "v2_34"

